substitutions:
  device_name: sonoff-s31
  friendly_name: sonoff s31
  update_interval: 5s


esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
esp8266:
  #board: esp01_1m
  board: esp12e

# Enable Home Assistant API
api:


http_request:
  verify_ssl: false
  timeout: 30s

ota:
  - platform: esphome
    password: !secret wifi_password
  - platform: http_request

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${friendly_name} Fallback"
    password: !secret wifi_password

web_server:
  port: 80  
  version: 3
  
captive_portal: 

# Device Specific Config

logger:
  baud_rate: 0 # (UART logging interferes with cse7766)
  logs:
    sensor: DEBUG # (Overide any global setting, to VERBOSE will spamming the cse7766 sensors)

uart:
  rx_pin: RX
  baud_rate: 4800
  parity: EVEN

button:
  - platform: template
    name: "${device_name} 韌體更新"
    entity_category: config
    on_press:
      - ota.http_request.flash:  
          url: "https://cdn.jsdelivr.net/gh/seanyan1994/esphome_s31@main/sonoff-s31.bin"
          md5_url: "https://cdn.jsdelivr.net/gh/seanyan1994/esphome_s31@main/sonoff-s31.md5"


  - platform: restart
    name: "重啟"


text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP address
      id: ip_address

  - platform: version
    name: ESPHome Version  

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff S31 Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "Sonoff S31 Status"
  # Overload Protection - When power > 1650W, turn off the relay
  - platform: template
    name: "Sonoff S31 Overload Protection"
    lambda: |-
      if (id(my_power).state > 1650) {
        return true;
      } else {
        return false;
        }
    on_press:
      - switch.turn_off: relay

sensor:
  - platform: cse7766
    current:
      name: "Sonoff S31 Current"
      accuracy_decimals: 2
      filters:
        - throttle_average: ${update_interval}
    voltage:
      name: "Sonoff S31 Voltage"
      accuracy_decimals: 2
      filters:
        - throttle_average: ${update_interval}
    power:
      name: "Sonoff S31 Power"
      accuracy_decimals: 2
      id: my_power
      filters:
        - throttle_average: ${update_interval}
    energy:
      name: "Sonoff S31 Energy"
      accuracy_decimals: 2
      filters:
        - throttle: ${update_interval}
    apparent_power: #(only available with version 2024.3.0 or greater)
      name: "Sonoff S31 Apparent Power"
      filters:
        - throttle_average: ${update_interval}
    power_factor: #(only available with version 2024.3.0 or greater)
      name: "Sonoff S31 Power Factor"
      accuracy_decimals: 2
      filters:
        - throttle_average: ${update_interval}

  - platform: total_daily_energy #(Optional, not specific to cse7766)
    name: "Sonoff S31 Daily Energy"
    power_id: my_power
    accuracy_decimals: 2

switch:
  - platform: gpio
    name: "Sonoff S31 Relay"
    pin: GPIO12
    id: relay
    restore_mode: RESTORE_DEFAULT_OFF

time:
  - platform: sntp #(required for total_daily_energy)
    id: my_time

status_led:
  pin:
    number: GPIO13
    inverted: True
